### ISSUE TITLE
SICK is down

### ISSUE THREAD

**Issue by dpthurst** [oberien/spirit-island-card-katalog#36]
SICK has been unresponsive to me for a few days now.

**Comment by oberien** [comment]
We were migrating our server to better hardware. The site is up and running again since about 12 hours. The new server has a different IP, so you might need to wait for your DNS service to timeout the entry and fetch the new IP, which might take up to 24 hours (TTL). For me it works now.

**Comment by dpthurst** [comment]
It is working for me now too.
