### ISSUE TITLE
Crashes on mobile

### ISSUE THREAD

**Issue by ColinAmos** [oberien/spirit-island-card-katalog#46]
A week or two ago the site started failing when I try to load it on mobile (iPhone 7 Plus, Chrome and Safari). It was kind of off-and-on at first, but now it fails pretty much every time. When I try to load the page, the browser will either show an error or crash. I've had no such troubles on desktop (and until recently, no such troubles on mobile).

**Comment by oberien** [comment]
I changed not a single thing on my side 1-2 weeks ago. The only change is a new Let'sEncrypt certificate 4 days ago, but that shouldn't matter.

Do you happen to have the error message / any idea on what the error might be?

**Comment by ColinAmos** [comment]
I was going to reply with a screenshot of the very generic error message, but then I had the thought to try restarting my phone. That fixed the issue! Quite a mystery as to what caused it; this has never happened with any website on my phone before. Oh well! Sorry for the false alarm.
