### ISSUE TITLE
Unique Powers FAQ redirects to an empty page on querki

### ISSUE THREAD

**Issue by locou** [oberien/spirit-island-card-katalog#48]
**Description:**
Unique Powers FAQ redirects to an empty page on querki

**Steps to reproduce:**
Open any unique power card
click on FAQ

**Suggestion for a fix:**
Since the power cards are named [NAME OF CARD] (owner: [NAME OF SPIRIT]) they are not found on querki
It should only be [NAME OF CARD]

Deleting the owner from the opened url redirects to the correct page.

**Comment by oberien** [comment]
Fixed via #47.
