### ISSUE TITLE
Using the card pictures with Spiritforge.app

### ISSUE THREAD

**Issue by Grenor123** [oberien/spirit-island-card-katalog#49]
Hi, I created an Excel sheet for myself to include all cards with text (Main goal is to have a list to compare english and german cards). I added an export function to json for the spiritforge.app website. For the pictures I needed an online source. So at the moment I use the card pictures from sick.oberen.de scaled placed approriately.
Is it ok for you, if I post those json files? I think the may be helpful for creating house ruled cards.

Greets
Grenot123

**Comment by oberien** [comment]
I'm not associated with Greater than Games. For these legal questions you should contact Eric Reuss or Dylan Thurston (e.g. via mail, bgg or discord). I've gotten the permission to use the card content and image sources directly from Dylan with the requirement of the legal notice at the top of the page and some modifications to this repository's licenses.

That said, I know that the images in SICK are linked to and included by the discord bot of the SI discord guild. I also think some versions of card content (csv and json) have been flying around in the discord as well.

**Comment by Grenor123** [comment]
Thx for the answer. I'll contact someone at GtG directly. If I get the ok from them, I would still like to know if it is ok for you because although I don't think this will create lots of traffic, it still creates some and I don't know who pays for it.

**Comment by oberien** [comment]
If you get the permission from >G, you can use / embed the images from sick.oberien.de.
