### ISSUE TITLE
Disable (or make optional) the automatic search

### ISSUE THREAD

**Issue by ppokellom** [oberien/spirit-island-card-katalog#50]
When entering letters in the search field, the page instantaneously searches for cards. That makes it very hard to use the side with restricted internet access. In this case the page loads after every entering of a letter, making it very slow and tedious to search for a card when having a bad connection.
I would appreciate, if the automatic search would be turned off, turned optional or if at least there was some delay from stopping entering letters to search.

**Comment by oberien** [comment]
I've added a debounce of 300ms. Could you please test if it works better for you now?

**Comment by oberien** [comment]
I changed it to be 300ms on desktop browsers and 1000ms for mobile browsers. Additionally, I added that the search will be performed when the search field loses focus (e.g. when closing the keyboard on iOS devices).

**Comment by ppokellom** [comment]
Awesome. Thanky you very much.
