### ISSUE TITLE
Add Horizons of Spirit Island Unique Power Cards

### ISSUE THREAD

**Issue by fifguy85** [oberien/spirit-island-card-katalog#52]
Thanks again for this amazing tool! 

With the release of Horizons there's the 4 new power cards for each of the 5 spirits that can now be added.

https://spiritislandwiki.com/index.php?title=Category:Horizons_of_Spirit_Island

**Comment by oberien** [comment]
I have seen this issue and am planning to do it, but I don't have the images for Horizons yet. I've contacted Dylan Thurston and asked him if he could provide me with them. Unfortunately, he doesn't have the time currently but will provide them at some point.

**Comment by oberien** [comment]
All Horizons cards and images have been added in b3c625a.
