### ISSUE TITLE
Dropbox Resources

### ISSUE THREAD

**Issue by tylerhartwig** [oberien/spirit-island-card-katalog#53]
Hi, I was trying to run the project locally and was taking a look through the processing. The readme mentions getting the resources from dropbox, is that still accessible?

**Comment by oberien** [comment]
The already built resources are available directly within the repo and ready for deployment. If you just want to run it locally, there is no need to manually build the resources.

To rebuild the resources (images) you need special access to a content dropbox with the original images, which I was provided with by Dylan Thurston.

**Comment by oberien** [comment]
The first iteration of SICK used scans. I scanned 3×3 cards at a time and used scripts to crop and derotate them. You can find those scripts in [/imgsprep/scans](https://github.com/oberien/spirit-island-card-katalog/tree/master/imgsprep/scans).

After some time >G allowed me to use scaled-down versions of the original images used for printing, which dthurston provides to me. Dylan stores those images as PDFs (one full-size card per page) which I then extract, scale down further and convert using the scripts in [/imgsprep](https://github.com/oberien/spirit-island-card-katalog/tree/master/imgsprep).

**Comment by tylerhartwig** [comment]
Thanks! that's super helpful, did you write the multicrop yourself? if so, impressive!

**Comment by oberien** [comment]
> ```
> # Revised by Fred Weinhaus ...................... revised 1/21/2017
> # Revised by Anthony Thyssen to add -b option ... revised 8/24/2010
> # Developed by Fred Weinhaus 1/30/2010 .......... revised 4/25/2015
> ```

I'm not one of those and definitely didn't write that script :)
