### ISSUE TITLE
People at Board Game Geek and the Spirit Island subReddit are wondering when/if the Nature Incarnate cards will be available on SICK

### ISSUE THREAD

**Issue by WhatHubris** [oberien/spirit-island-card-katalog#55]
People at the Board Game Geek and the Spirit Island subReddit forums are wondering when/if the Nature Incarnate cards will be available on SICK. I am wondering too.  Thank you for producing a great resource that I use often while playing Spirit Island!

**Comment by oberien** [comment]
I am holding off until I can hold the backed game in my hands here in the EU.

**Comment by WhatHubris** [comment]
Thank you, and I hope it arrives to you quickly!

**Comment by oberien** [comment]
As I finally received my BackerKit copy of Nature Incarnate today, SICK is now updated to include all 73 new Nature Incarnate cards and the card-update of Draw Towards a Consuming Void.

8ee2a33

**Comment by WhatHubris** [comment]
That's great! I checked the catalog, and I can't manage to get any Nature Incarnate cards to show up when I search. Will there be a lag time before it's available for searches?

**Comment by WhatHubris** [comment]
Never mind--Control-F5 refresh worked for me.
