### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ivan-aidun** [oberien/spirit-island-card-katalog#60]
Hi there, I've been using your SICK a lot, it's a really great resource! I've noticed a couple typos in the card texts, often because cards won't show up correctly when I'm searching, and it seemed like this is perhaps the way to reach out about them.
- Favors of Story and Season currently says "If they have at least 3 Dahan among their lands, they gain 10Energy", where it should say "1 Energy"
- Turmoil's Touch currently says its elements are "Sun, Animal, Air, Plant", where it should say "Sun, Moon, Air, Plant"
- Infestation of Venomous Spiders has a semicolon after the threshold rather than a colon, so it says "2 Air, 2 Earth, 3 Animal;" instead of "2 Air, 2 Earth, 3 Animal:"

Thanks so much for creating this great site!

**Comment by oberien** [comment]
Thanks for the finds and the report. It's fixed now.
